### ISSUE TITLE
Missing dependency: bzip2

### ISSUE THREAD

**Issue by cinghiale** [bincrafters/conan-boost#1]
While installing some boost dependencies, conan install exists with this output:

     bzip2/1.0.6@conan/stable: Not found in local cache, looking in remotes...
     bzip2/1.0.6@conan/stable: Trying with 'conan-transit'...
     bzip2/1.0.6@conan/stable: Trying with 'conan-center'...
     bzip2/1.0.6@conan/stable: Trying with 'bincrafters'...
     bzip2/1.0.6@conan/stable: Trying with 'conan.io'...
    ERROR: Unable to find 'bzip2/1.0.6@conan/stable' in remotes

## The dependencies
    [requires]
    Boost.Coroutine2/1.64.0@bincrafters/stable
    Boost.Iterator/1.64.0@bincrafters/stable

## The remotes
    conan-transit https://api.bintray.com/conan/conan/conan-transit True
    conan-center https://api.bintray.com/conan/conan/conan-center True
    bincrafters https://api.bintray.com/conan/bincrafters/public-conan True
    conan.io https://server.conan.io True

**Comment by cinghiale** [comment]
Forgot to add the output of the search command:

    $ conan search -r conan-transit bzip2*
    Existing package recipes:
    
    bzip2/1.0.6@kmaragon/stable
    bzip2/1.0.6@lasote/ci
    bzip2/1.0.6@lasote/stable
    bzip2/1.0.6@orhun/testing

    $ conan search -r conan-center bzip2*
    There are no packages matching the bzip2* pattern

    $ conan search -r bincrafters bzip2*
    There are no packages matching the bzip2* pattern

**Comment by solvingj** [comment]
Thanks for the feedback, looking into this now, I believe I know what the issues is.

**Comment by solvingj** [comment]
There seems to have been a delay on bzip2 package getting promoted to conan-center from the Conan teams testing repository.  I will ask them to expedite the promotion of the bzip2 package. 

In the meantime, please add the "conan-community" remote to find this package: 

`https://bintray.com/conan-community`

Here is the command: 
`conan remote add conan-community https://api.bintray.com/conan/conan-community/conan`

**Comment by solvingj** [comment]
We received confirmation that this package will get promoted to conan-center ASAP, thanks for bringing it to our attention.  Everyone on the bincrafters team and our CI recipes had conan-community as a repository, however this should not be a requirement, so I've opened a ticket to remove it from all CI moving forward.

**Comment by solvingj** [comment]
Good news, bzip2 is now in conan-center.
